import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/(AdminPanel)/Navbar/Navbar";
import SideBar2 from "@/components/(AdminPanel)/Sidebar/Sidebar2";
import NotificationBar from "@/components/(AdminPanel)/NotificationBar/NotificationBar";
import { NotificationProvider } from "@/components/(AdminPanel)/NotificationBar/NotificationContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ticket Master",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
  
  <NotificationProvider>


<div className="flex"> 
<SideBar2/>

<div className="w-full bg-gray-50">
<Navbar/>

<div className="p-4 pt-8 w-full flex flex-wrap flex-col justify-between">

      {children}
</div>


</div>

<NotificationBar />


{/* <SideBar3/> */}
</div>


        
        
</NotificationProvider>
        </body>
    </html>
  );
}
